# Generated by Django 3.2.3 on 2022-05-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusParking', '0003_alter_parking_time_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='price',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
