# Generated by Django 3.2.3 on 2022-05-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='number_car',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
